on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: temurin
    - run: wget https://raw.githubusercontent.com/dwijnand/sbt-extras/d7d876d6868ae1d262a7de38cbffbb8521c4233c/sbt
    - run: chmod +x ./sbt
    - run: ./sbt -v "reload plugins" "show libraryDependencies"
    - run: cat project/plugins.sbt | sort > tmp && diff tmp project/plugins.sbt
